name: Dayly Classical Strategy Scan for Crypto

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:      # Exécution manuelle

jobs:
  validate-classical-strategies:
    runs-on: ubuntu-22.04
    env:
      REAL_EMAIL_SMTP_SERVER: ${{ secrets.REAL_EMAIL_SMTP_SERVER }}
      REAL_EMAIL_SMTP_PORT: ${{ secrets.REAL_EMAIL_SMTP_PORT }}
      REAL_EMAIL_LOGIN: ${{ secrets.REAL_EMAIL_LOGIN }}
      REAL_EMAIL_PASSWORD: ${{ secrets.REAL_EMAIL_PASSWORD }}
      REAL_EMAIL_TO_PROD: ${{ secrets.REAL_EMAIL_TO_PROD }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -e ".[dev]"

    - name: Run validation
      run: python scripts/run_classical_scan_crypto.py
